# Generated by Django 4.1 on 2022-08-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceobject',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_objects.category'),
        ),
    ]
