# Generated by Django 4.1 on 2022-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_objects', '0004_eamil'),
    ]

    operations = [
        migrations.AddField(
            model_name='eamil',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
