# Generated by Django 4.1 on 2022-09-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_objects', '0005_eamil_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eamil',
            new_name='Email',
        ),
    ]
